version: "3.8"

services:
  django:
    build:
      context: ./Computex
    container_name: django-container
    ports:
      - 8000:8000
    depends_on:
      - postgres  

  react:    
    build:
      context: ./computex
    container_name: react-container
    ports:
      - 80:80
    depends_on:
      - django

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=computex
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: